import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Test from "./_test";
import { fetchData } from "../../utils/fetchCalls";
import { GetStaticProps } from "next";
import { useEffect } from "react";
import { getData } from "../../utils/fetchCalls";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    getData().then((data) => console.log(data));
  }, []);
  return (
    <>
      <Head>
        <title>FitLit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Test />
      </main>
    </>
  );
}
